/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IRr6DSWWzm0
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Archivo } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Unlock the Power of PDF with AI
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400 mt-4">
                  Our PDF AI application revolutionizes the way you work with documents. Automate text extraction, image
                  recognition, and document organization for unparalleled efficiency.
                </p>
                <div className="space-x-4 mt-6 mb-10">
                  <Link
                    className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Get Started
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Revolutionize Your PDF Workflow</h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Our PDF AI application offers a suite of powerful features to streamline your document management.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Automated Text Extraction</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Effortlessly extract text from your PDFs with our advanced optical character recognition (OCR)
                  technology.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Image Recognition</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Unlock the hidden insights in your PDF documents by automatically identifying and categorizing images.
                </p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-lg font-bold">Document Organization</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Streamline your workflow by organizing your PDFs into searchable, tagged collections.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
