/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mAed0K4WpJe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Archivo } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Navbar() {
  return (
    <header className="bg-gray-900 text-gray-50 dark:bg-gray-950 dark:text-gray-50">
      <div className="container flex items-center justify-between px-4 py-4 md:px-6 md:py-5">
        <Link className="flex items-center gap-2 font-bold" href="#">
          <FileIcon className="h-6 w-6" />
          <span>PDF AI</span>
        </Link>
        <nav className="hidden space-x-4 md:flex">
          <Link className="hover:text-gray-300" href="/home">
            Home
          </Link>
          <Link className="hover:text-gray-300" href="/chat">
            Chat
          </Link>
        </nav>
        <div className="flex items-center gap-2">
          <Link
            className="rounded-md px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:hover:bg-gray-800 dark:focus-visible:ring-gray-300"
            href="#"
          >
            Log in
          </Link>
          <Link
            className="rounded-md bg-gray-50 px-4 py-2 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-800 dark:text-gray-50 dark:hover:bg-gray-700 dark:focus-visible:ring-gray-300"
            href="#"
          >
            Sign up
          </Link>
        </div>
      </div>
    </header>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}
